### ISSUE TITLE
How is the dropdown control type used?

### ISSUE THREAD

**Issue by dreness** [Hi-Rez/Youi#3]
Hi! I celebrate the entire Hi-Rez catalog :)

I'm trying to figure out if Youi can host something like a NSPopupButton populated with a hard-coded list of possible values for a param (composite modes, for example). I see a dropdown control type, and can even get it to appear, but I don't know how to populate it or rig it up because I'm a swift noob. Any help?

**Comment by rezaali** [comment]
Sorry for the delay, the easiest way to use the dropdown is to pass it a StringParameter with options: 
` 
StringParameter("Spectrum Filter", "Blackman", ["Hanning-N", "Hanning-D", "Hamming", "Blackman", "None"], .dropdown)
`
